services:
  app:
    build:
      dockerfile: ./php/Dockerfile
      target: "${BUILD_TARGET:-app_dev}"
    volumes:
      - ./app:/var/www/html
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      REDIS_HOST: cache
      REDIS_PORT: ${REDIS_PORT}
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
